name=Audio Over OSC
version=0.0.1
author=Phil Schatzmann
maintainer=Phil Schatzmann
sentence=Arduino Audio Over OSC
paragraph=Audio Library to send and receive audio over OS
category=Signal Input/Output
url=https://github.com/pschatzmann/arduino-aoo
architectures=*